- name: set chrome release apt gpg key
  become: yes
  ansible.builtin.apt_key:
    url: "https://dl-ssl.google.com/linux/linux_signing_key.pub"
    state: present

- name: add chrome repository
  become: yes
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"
    update_cache: true

- name: install chrome
  become: yes
  ansible.builtin.apt:
    name: google-chrome-stable
    update_cache: true
