- name: install flatpak packages
  become: yes
  ansible.builtin.apt:
    pkg: "flatpak"
    state: present

- name: add the flathub flatpak repository remote to the user installation
  become: yes
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

- name: install flatpak packages
  become: yes
  community.general.flatpak:
    name: "{{ flatpak_pkgs }}"
  when: flatpak_pkgs is defined
