- name: configure git - user email
  git_config:
    name: user.email
    scope: global
    value: "{{ my_email }}"
- name: configure git - name
  git_config:
    name: user.name
    scope: global
    value: "{{ my_fullname }}"
- name: configure git - username
  git_config:
    name: user.username
    scope: global
    value: "{{ my_github_username }}"
- name: configure git - user signing key
  git_config:
    name: user.signingKey
    scope: global
    value: "{{ my_git_signkey }}"
- name: set git config - always sign gpg
  git_config:
    name: commit.gpgsign
    scope: global
    value: "true"
- name: set git config - editor
  git_config:
    name: core.editor
    scope: global
    value: "code-insiders --wait"
- name: set git defauklt branch
  git_config:
    name: init.defaultBranch
    scope: global
    value: "main"
