- name: import tasks/dev/git.yaml
  include: tasks/dev/git.yaml
  tags: git
- name: import tasks/dev/go.yaml
  include: tasks/dev/go.yaml
  tags: go
- name: import tasks/dev/wails.yaml
  include: tasks/dev/wails.yaml
  tags: wails
