- name: get latest release version of terraform from github
  github_release:
    user: hashicorp
    repo: terraform
    action: latest_release
  register: terraform_release

- name: clean up terraform version number
  set_fact:
    terraform_version: "{{ terraform_release.tag | regex_replace('^v', '') }}"

- name: download & extract terraform zip
  become: yes
  unarchive:
    src: "https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip"
    dest: /usr/local/bin
    remote_src: yes

  # when: terraform_release.changed
- name: get latest release version of gh cli from github
  github_release:
    user: cli
    repo: cli
    action: latest_release
  register: gh_cli_release

- name: get gh cli version number w/o v
  set_fact:
    gh_cli_version: "{{ gh_cli_release.tag | regex_replace('^v', '') }}"

- name: install gh cli .deb package from github
  become: yes
  apt:
    deb: https://github.com/cli/cli/releases/download/{{ gh_cli_release.tag }}/gh_{{ gh_cli_version }}_linux_amd64.deb

- name: get latest release version of lazydocker from github
  github_release:
    user: jesseduffield
    repo: lazydocker
    action: latest_release
  register: lazydocker_release

- name: clean up lazydocker version number
  set_fact:
    lazydocker_version: "{{ lazydocker_release.tag | regex_replace('^v', '') }}"

- name: download & extract lazydocker tgz
  become: yes
  unarchive:
    src: "https://github.com/jesseduffield/lazydocker/releases/download/{{ lazydocker_release.tag }}/lazydocker_{{ lazydocker_version }}_Linux_x86_64.tar.gz"
    dest: /usr/local/bin
    remote_src: yes

- name: get latest release version of k3sup from github
  github_release:
    user: alexellis
    repo: k3sup
    action: latest_release
  register: k3sup_release

- name: clean up k3sup version number
  set_fact:
    k3sup_version: "{{ k3sup_release.tag | regex_replace('^v', '') }}"

- name: Download and install k3sup from github
  become: yes
  get_url:
    url: https://github.com/alexellis/k3sup/releases/download/{{ k3sup_version }}/k3sup
    dest: /usr/local/bin/k3sup
    mode: "0755"
