- name: setup ~/Applications folder
  file:
    path: "/home/{{ lookup('env','USER') }}/Applications"
    state: directory

- name: get latest release version of neovim from github
  github_release:
    user: neovim
    repo: neovim
    action: latest_release
  register: neovim_release

- name: download neovim appimage from github
  get_url:
    url: "https://github.com/neovim/neovim/releases/download/{{ neovim_release.tag }}/nvim.appimage"
    dest: "/home/{{ lookup('env','USER') }}/Applications/nvim.appimage"
    mode: "0755"
