# Scrape module from https://github.com/particledecay/ansible-scrape/blob/master/scrape.py

- name: setup ansible module folders if they do not exist
  file:
    path: "{{ item }}"
    state: directory
    mode: "0700"
    owner: "{{ lookup('env','USER') }}"
    group: "{{ lookup('env','USER') }}"
  with_items:
    - "/home/{{ lookup('env','USER') }}/.ansible/modules"
- name: placing scrape.py andible module
  copy:
    src: files/home/.ansible/modules/scrape.py
    dest: "/home/{{ lookup('env','USER') }}/.ansible/modules/scrape.py"
    owner: "{{ lookup('env','USER') }}"
    group: "{{ lookup('env','USER') }}"
