- name: add ansible-pull sudoer file
  become: yes
  file:
    path: /etc/sudoers.d/ansible_pull
    state: touch
    owner: root
    group: root
    mode: 0440

- name: allow ansible-pull with no password
  become: yes
  lineinfile:
    path: /etc/sudoers.d/ansible_pull
    line: "dustin ALL=(ALL) NOPASSWD: /usr/bin/ansible-pull"
    # state: present
    validate: "/usr/sbin/visudo -cf %s"

- name: add auto-cpufreq sudoer file
  become: yes
  file:
    path: /etc/sudoers.d/auto_cpu_freq
    state: touch
    owner: root
    group: root
    mode: 0440

- name: allow auto-cpufreq with no password
  become: yes
  lineinfile:
    path: /etc/sudoers.d/auto_cpu_freq
    line: "dustin ALL=(ALL) NOPASSWD: /snap/bin/auto-cpufreq"
    # state: present
    validate: "/usr/sbin/visudo -cf %s"

- name: add systemd logid service sudoer file
  become: yes
  file:
    path: /etc/sudoers.d/logid
    state: touch
    owner: root
    group: root
    mode: 0440

- name: allow systemd logid service with no password
  become: yes
  lineinfile:
    path: /etc/sudoers.d/logid
    line: "dustin ALL=(ALL:ALL) NOPASSWD: /usr/bin/systemctl restart logid.service"
    # state: present
    validate: "/usr/sbin/visudo -cf %s"

- name: add systemd suspend service sudoer file
  become: yes
  file:
    path: /etc/sudoers.d/suspend
    state: touch
    owner: root
    group: root
    mode: 0440

- name: allow systemd suspend service with no password
  become: yes
  lineinfile:
    path: /etc/sudoers.d/suspend
    line: "dustin ALL=(ALL:ALL) NOPASSWD: /usr/bin/systemctl suspend"
    # state: present
    validate: "/usr/sbin/visudo -cf %s"
