# Defined for use when you update to the latest version of
# Ubuntu, and a software vendor has not yet updated thier PPA
# COmment this out when the PPAs have been updated.

docker_ubuntu_version: impish
insync_ubuntu_version: impish
tailscale_ubuntu_version: impish
sirikali_ubuntu_version: xUbuntu_21.10
