- name: add docker's public pgp key to the apt keyring
  become: yes
  ansible.builtin.apt_key:
    id: "9DC858229FC7DD38854AE2D88D81803C0EBFCD88"
    url: "https://download.docker.com/linux/ubuntu/gpg"

- name: add docker's stable apt repository
  become: yes
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    filename: docker
    update_cache: true
  when: docker_ubuntu_version is undefined

- name: add docker's stable apt repository for {{ docker_ubuntu_version }}
  become: yes
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ docker_ubuntu_version }} stable"
    state: present
    filename: docker
    update_cache: true
  when: docker_ubuntu_version is defined

- name: install docker dependencies
  become: yes
  ansible.builtin.apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: present

- name: remove docker apt packages from the ubuntu repository
  become: yes
  ansible.builtin.apt:
    pkg:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent

- name: install docker ce
  become: yes
  ansible.builtin.apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose
    state: present

- name: add "{{ lookup('env','USER') }}" user to docker group
  become: yes
  user:
    name: "{{ lookup('env','USER') }}"
    groups: docker
    append: yes
